### ISSUE TITLE
Parent methods called multiple times after child reload

### ISSUE THREAD

**Issue by ski629** [Aaronius/penpal#18]
Thank you for writing this great library! It has been very easy to work with outside of this one issue.

After a child is reloaded, any methods that it calls on the parent are executed on the parent side multiple times. The child only receives one response, but the parent executes the method an additional time for every time the child is reloaded. 

For example, if the child is reloaded three times, and then calls a parent method once, the parent will execute that method 4 times, and return only the first result to the child. 

This is easy to reproduce by placing a console.log statement inside the 'add' method in the usage example, and right clicking inside the child pane and clicking 'reload frame'.

This is a fairly significant problem if the parent method has any side effects. I have not had a chance to look into the cause yet.

**Comment by Aaronius** [comment]
Thanks for reporting this. Yeah, sounds like a bug. I'll take a look as soon as I can. If you figure it out before then, a PR would be excellent.

**Comment by Aaronius** [comment]
Fixed in 3.0.2.

**Comment by ski629** [comment]
Thank you Aaron!
