### ISSUE TITLE
Cannot read property 'parentWindow' of null

### ISSUE THREAD

**Issue by srhyne** [Aaronius/penpal#27]
@Aaronius we are using Penpal for [embedded lessons](https://vimeo.com/316903371) in ConveYour.com. We ❤️ it! Thank you! 

I just upgraded from 3.0.7 to 3.1.0 and now we are getting this exception often. Here's the related line. 

https://github.com/Aaronius/penpal/blob/843476f823b2b896b471ab02728aa8c715aaaf6c/src/index.js#L392

It looks like in the previous version this variable was set prior to handleMessage method being created so held in a closure (right?). 

What should I change in my setup to make sure I'm compliant with this change? Thank you!

**Comment by srhyne** [comment]
More on this.. It seems as though, this handleMessage would only fire when the parent receives a message from the child and that's only going to happen when the child is already in the DOM. I'm going to try to do some console log's on this to figure out what event or iframe state is causing this.

**Comment by Aaronius** [comment]
@srhyne I ended up fixing this issue in [this commit](https://github.com/Aaronius/penpal/commit/59c7231892b2f04ad21c8af48dc564589ce64507) and releasing it in version 3.1.1. It doesn't resolve the concerns I outlined in https://github.com/Aaronius/penpal/pull/28#issuecomment-469872375, though. I'm still thinking that through.
