### ISSUE TITLE
Please make connectToParent and connectToChild accept a generic type parameter.

### ISSUE THREAD

**Issue by marlon-tucker** [Aaronius/penpal#47]
Hello,

In the 3.x branch, the TS Typings for these methods were generic and thus allowed the returned promise to be correctly typed. In the 5.x branch at the moment, this promise is typed to `CallSender` which is just a function dictionary and so there's no type safety.

Something like this would keep compatibility

```
connectToParent<TParent = CallSender>(...)
``` 

So if a generic parameter isn't provided, it falls back to `CallSender`.

Am happy to provide a pull request if you want.

**Comment by Aaronius** [comment]
@marlon-tucker Please do! I don't have a lot of experience with TS so a pull request would be helpful. Thanks for filing the issue.
