### ISSUE TITLE
CI and Browser testing

### ISSUE THREAD

**Issue by loganvolkers** [Aaronius/penpal#5]
It would nice to see CI running for this project and for that to include some browser testing. 😄 

I noticed that IE support is only for IE 10+, but it's nice to see that as a badge on the project page:

![image](https://cloud.githubusercontent.com/assets/1157086/25244782/ef9a9638-25b6-11e7-9990-6a53dcfcf483.png)

Sauce Labs has free browser testing for open source projects: https://saucelabs.com/open-source https://saucelabs.com/beta/signup/OSS/None

**Comment by Aaronius** [comment]
Yes! I agree. My schedule for the several weeks does not look promising for this work (trip to California, conference in Switzerland, moving to a new house) but I really would like to do this. I'm willing to give rights to anyone who may want to help out with this.

**Comment by Aaronius** [comment]
Fixed. There was one test failing for IE 10 that could probably be fixed (it's a specific scenario that most people probably wouldn't run into), but IE 10 usage is so low I decided I didn't want to deal with it. I've said that v11 is the only IE supported now. I still need to make the tests run on iOS and Android.

**Comment by loganvolkers** [comment]
❤️ 😍
