### ISSUE TITLE
Connection promise gets rejected with error if destroyed by the user

### ISSUE THREAD

**Issue by h15ter** [Aaronius/penpal#51]
Imagine the following common scenario:
1) I have a single-page application.
2) When user comes to a specific area, I create an iframe and connect to it with penpal.
3) When user leaves that area, I destroy the connection and remove the iframe.

In this scenario, if user leaves the area *before* connection is established (it may take time due to network latency etc), connection promise is always resolved with an error logged in the console. This is nasty because from code perpective I do it right by calling `connection.destroy()` to let penpal know the connection is destroyed on purpose, so it's not an error and shouldn't be logged like that.

In order to hide the error, I have to eat all exceptions from connection.promise which potentially hides real connection problems.

Here is the code sample:
```javascript
const page = document.getElementById('page');
const iframe = document.createElement('iframe');
iframe.src = 'child.html';

const connection = Penpal.connectToChild({iframe, debug: true });
page.appendChild(iframe);

// Emulate cleanup happening when user is leaving the page.
setTimeout( () => {
	connection.destroy();
	page.removeChild(iframe);
}, 0);

```

And here is the error logged in console:
[Error in console](https://i.imgur.com/MLodAHF.jpg)

And here is the workaround I use:
```javascript
const connection = Penpal.connectToChild({iframe, debug: true });
connection.promise.catch(()=>{}); // Ugly because it may hide real connection problems.
page.appendChild(iframe);
```

Ideally connection promise shouldn't get rejected with a error if connection was destoryed by a user. It should just never resolve, same way as child methods work on a destroyed connection. 
We should see this error only if connection was aborted by penpal (for instance, by iframe watcher).

**Comment by Aaronius** [comment]
This change was released in v6. Thanks!

**Comment by cimak** [comment]
@Aaronius if was a feature, not a bug! It is bug now, we have memory leaks, take a look:

```ts
const connection = connect({
    // ...
    timeout: 60_000,
});

cancelButton.classList.remove('hidden'); // show "cancel" button
cancelButton.addEventListener('click', () => {
    connection.destroy();
});

const remote = await connection.promise; // pending FOREVER (!) if user clicks "cancel" within that 1 minute timeout

cancelButton.classList.add('hidden'); // hide "cancel" button
```

I think it should work similarly to `fetch()` which you can abort using signals:
```ts
const abortController = new AbortController();

abortController.abort('cancelled by user');

try {
    await fetch('/ping', { method: 'GET', signal: abortController.signal });
    console.log('got response');
} catch (error) {
    console.log('fetch failed:', error);
}
```
will print `fetch failed: cancelled by user`.

**Comment by cimak** [comment]
Sure:
```js
async function test() {
    const largeArr = createLargeArray();
    
    const remote = await connection.promise; // if pending forever...
    
    // ...then largeArr is kept in memory forever, waiting to be logged.
    console.log(largeArr.length);
}
```
`connection.promise` not rejecting when cancelled is also completely counter intuitive. Look how native APIs works in the exact same situation:
- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API `fetch()` rejects/throws when cancelled (using singal).
- https://developer.mozilla.org/en-US/docs/Web/API/Animation/finished - reject/throws when animation is cancelled (using `animation.cancel()`)

**Comment by cimak** [comment]
>I assume you're referring to largeArr from one of the methods you're exposing through Penpal? 

no

> If you remove all references to connection and your messenger instance, is largeArr eventually garbage collected?

`largeArr` can't be garbage collected as long as the connection promise is in pending state.
JavaScript keeps it in memory because _**it might be**_ needed after await.

Only after the await resolves (and `largeArr` is logged) or rejects, JavaScript knows it can clean it up.

So if the `connection.promise` never resolves, then the function never moves on, and `largeArr` is never let go - it's stuck in memory forever.

**Comment by Aaronius** [comment]
Oh, right, I understaind what you're describing now. Yeah, I do think I need to address this, but probably in a major version. Thanks for providing your input!
