### ISSUE TITLE
Latest chrome update breaks the penpal

### ISSUE THREAD

**Issue by ricklang** [Aaronius/penpal#54]
I am using penpal 5.0.0 for cross domain message. Basically I have three web applications A, B, and C on different domains. Both A and B load C as iframe and write/read something to the iframe, so A and B can exchange information. It was all working fine. But today it is not working any more. I check the chrome version It is the latest Chrome 84.0.4147.89 and just updated yesterday on my machine. The same applications are working fine on Edge and Firefox. Does anybody know what the latest change on chrome might break my application?

**Comment by Aaronius** [comment]
Thanks for reporting this @ricklang. When you say "it is not working any more", what behavior are you seeing that's incorrect? Are you receiving any errors? Is this somewhere public where I could debug further?

**Comment by Aaronius** [comment]
I haven't heard anything back, so I'm going to close this. If you have more information, please share
